notifications:
  email: false

language: node_js

node_js:
  - '0.10'

branches:
  only:
    - master

before_script:
  - "curl -O http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar"
  - "java -jar selenium-server-standalone-2.43.1.jar 2>&1 >/dev/null &"

script: "sleep 10 && ./node_modules/.bin/mocha"
